eureka:
  client:
    serviceUrl:
      defaultZoneDomain: ${EUREKA_DISCOVERY_SERVER_URI_PEERS:http://172.31.49.49}
      defaultZone: ${eureka.client.serviceUrl.defaultZoneDomain}:8761/eureka/

spring:
  sleuth:
    propagation-keys: uuid
    log:
      slf4j:
        whitelisted-mdc-keys: uuid
  jpa:
    open-in-view: false

logging:
  pattern:
    level: "%5p [${spring.application.name:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-},%X{uuid:-}]"
  level:
    com:
      appme: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"