spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barbers_db?useSSL=false
    username: root
    password: Admin&02
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.zoho.com
    username: no-reply@zamacueca.com
    password: n0R3pl4y&
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

mybatis:
  type-aliases-package: com.gaidar.model
  mapperLocations: classpath*:**/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

flyway:
  password: ${FLYWAY_API_USERS_PASSWORD:${spring.datasource.password}}
  user: ${FLYWAY_API_USERS_USER:${spring.datasource.username}}
  url: ${FLYWAY_API_USERS_URL:${spring.datasource.url}}

logging:
  level:
    com:
      gaidar: debug