spring:
  datasource:
    url: ${BARBERS_API_URL}/barbers_db?useSSL=false
    username: ${BARBERS_API_USER}
    password: ${BARBERS_API_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
  mail:
    default-encoding: UTF-8
    host: smtp.zoho.com
    username: no-reply@zamacueca.com
    password: n0R3pl4y&
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

mybatis:
  type-aliases-package: com.gaidar.model
  mapperLocations: classpath*:**/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

flyway:
  password: ${FLYWAY_API_USERS_PASSWORD:${spring.datasource.password}}
  user: ${FLYWAY_API_USERS_USER:${spring.datasource.username}}
  url: ${FLYWAY_API_USERS_URL:${spring.datasource.url}}

logging:
  level:
    com:
      gaidar: debug

cloud:
  aws:
    credentials:
      accessKey : AKIAI5RGIYGAPFPSHVIA
      secretKey : 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
    region: us-west-1
    s3:
      bucket: images-zamacueca-prod
    stack:
      auto: false