spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appartame_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
  type-aliases-package: com.appme.model
  mapperLocations: classpath*:**/repository/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
