spring:
  datasource:
    url: ${APM_V_OAUTH_API_URL}?useSSL=false&serverTimezone=UTC
    username: ${APM_V_OAUTH_API_USER}
    password: ${APM_V_OAUTH_API_PASSWORD}

mybatis:
  type-aliases-package: com.appme.model
  mapperLocations: classpath*:**/repository/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30