spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true

flyway:
  url: jdbc:mysql://localhost:3306/users_db
  password: root
  user: root

logging:
  level:
    com:
      gaidar: debug