spring:
  datasource:
    url: jdbc:mysql://mysqldb-instance1.cbusy8rh4ihf.us-east-1.rds.amazonaws.com:3306/SICMX001?useSSL=false
    username: msgAdm01
    password: adm1n&0102
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

flyway:
  password: ${FLYWAY_API_USERS_PASSWORD:${spring.datasource.password}}
  user: ${FLYWAY_API_USERS_USER:${spring.datasource.username}}
  url: ${FLYWAY_API_USERS_URL:${spring.datasource.url}}