spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SICMX001?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.mgonsal.users.domain
  mapperLocations: classpath*:**/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

flyway:
  password: ${FLYWAY_API_USERS_PASSWORD:${spring.datasource.password}}
  user: ${FLYWAY_API_USERS_USER:${spring.datasource.username}}
  url: ${FLYWAY_API_USERS_URL:${spring.datasource.url}}