spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SICMX001?useSSL=false
    username: CVJSIC02
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

flyway:
  password: ${FLYWAY_API_USERS_PASSWORD:${spring.datasource.password}}
  user: ${FLYWAY_API_USERS_USER:${spring.datasource.username}}
  url: ${FLYWAY_API_USERS_URL:${spring.datasource.url}}